### ISSUE TITLE
Stats are reset when re-balancing users across slave nodes

### ISSUE THREAD

**Issue by heyman** [locustio/locust#1168] opened 2019-11-20 16:54 UTC
When running locust with `--reset-stats` in distributed mode, the stats are reset every time a new slave connects (when the re-balancing of the simulated users occur). The stats should only be reset when the initial hatching is complete, and not when re-balancing users.

**Comment by max-rocket-internet** [comment] 2019-11-21 10:47
I am not using `--reset-stats` option, I'm using the default docker image `locustio/locust:0.13.1` and locust is started like this:

```
# Slave
/usr/local/bin/python /usr/local/bin/locust --slave --locustfile=/mnt/locust/main.py --host=https://xxxxx.com --master-host=locust-xxx

# Master
/usr/local/bin/python /usr/local/bin/locust --master --locustfile=/mnt/locust/main.py --host=https://xxxxx.com
```

But I still see this issue 🙂

**Comment by heyman** [comment] 2019-11-21 13:44
Hm, that's strange. I'm not able to reproduce the issue without --reset-stats. I guess I have to do some more digging (I'll try and see if I can reproduce it using the Docker image).

**Comment by max-rocket-internet** [comment] 2019-11-22 10:50
OK let me know if you want me to debug or test something.

**Comment by matti** [comment] 2019-11-27 12:09
I'm also having the same issue as @max-rocket-internet 
![Locust](https://user-images.githubusercontent.com/3893/69722366-8fa78400-111f-11ea-8ff3-04152bba644d.png)

**Comment by max-rocket-internet** [comment] 2020-01-02 15:35
Still seeing this in version `0.13.5`:

![Screen Shot 2020-01-02 at 16 34 29](https://user-images.githubusercontent.com/8859277/71675320-cce5de00-2d7d-11ea-89ff-3d6181bab742.png)

**Comment by carstendev** [comment] 2020-01-23 12:30
I was able to replicate this or a (related?) issue, by doing the following:
- Start a test without ```--reset-stats``` with 500 max users and a hatch rate of 1
- Lower the number of max users after one minute (still during the hatching phase) to 450

Locust then proceeds to calculate ```users_to_kill = 500 - 450``` and kills 50 users immediately. 

Issue here is, that as the hatching is still ongoing 50 of the at this point only 60 spawned users are killed. I would expect locust to kill users based on the actual spawned users, not just the max setting.

If this is in fact not the same issue, I can also open another issue for this.

**Comment by heyman** [comment] 2020-01-23 15:45
I've managed to reproduce the issue using the steps described by @carstendev. It's actually a different issue than the original post, but with similar symptoms.

I'm working on a fix now.

**Comment by heyman** [comment] 2020-01-23 16:56
I've now pushed changes (576f7eae2375b454d13499f3b20055d85ae3d301) that should hopefully fix this. Would be great if someone could try out the latest master to confirm that the issue has been fixed.

**Comment by carstendev** [comment] 2020-01-24 09:07
I've tried to reproduce the issue with the latest master, but it seems to be fixed now 👍.

**Closed** 2020-01-24 12:35 UTC
Labels: bug

**Comment by max-rocket-internet** [comment] 2020-01-27 09:59
Awesome, thanks @heyman!
