### ISSUE TITLE
Test metrics are not preserved on Stop click in the UI

### ISSUE THREAD

**Issue by niconphantom** [locustio/locust#883] opened 2018-09-14 17:45 UTC
### Description of issue / feature request

In Locust 0.8.1, when Stop button is clicked in the UI, RPS, latency and other test metrics are frozen and preserved until # of users is changed and another test is performed. 

In 0.9.0 this is not the case and when Stop is clicked, RPS and other counters slowly go down from let's say X RPS to 0 RPS. This is super inconvenient when manual testing is performed and the test metrics should be documented. 

More than that, if I export a CSV with request details right after I click stop and then download the same file after X seconds, I see totally different numbers. So it takes some time for counters to reach 0 and each file download shows inconsistent result.

### Expected behavior

Test metrics should be preserved in the UI and on CSV download once the Stop button was clicked.

### Actual behavior

Test metrics slowly change from X to 0 in both UI and on CSV download.

### Steps to reproduce (for bug reports)

1) Start any test with 1 master and X slaves on single machine with UI mode.
2) Open UI and start the test. Let it run for some seconds until you see RPS value > than 0.
3) Click Stop in the UI
4) Wait some seconds and you should see RPS and other metrics slowly changing from X to 0.

**Comment by cyberw** [comment] 2019-11-02 19:01
Closing due to inactivity.

**Comment by heyman** [comment] 2019-11-06 10:45
I just successfully reproduced this, and I do think it should be classified as a bug.

**Comment by heyman** [comment] 2019-11-06 12:56
Should be fixed by 3df524d5ed92016d2d48d924de7c41dca2db8196.

**Closed by heyman** 2019-11-06 12:56 UTC
Labels: bug
