### ISSUE TITLE
how can I send https request  with locust when I already have been authentication..

### ISSUE THREAD

**Issue by turgayh** [locustio/locust#966] opened 2019-02-20 08:00 UTC
### Description of issue / feature request

Hi .. I'm working about load testing and I'm beginner.

İ want to get request a page that protected (login required)..

My code 

```
from locust import HttpLocust, TaskSet, task

class WebsiteTasks(TaskSet):
    def on_start(self):
        self.login()
    def login(self):
        response = self.client.get("/admin/")
        csrftoken = response.cookies['csrftoken']
        response = self.client.post("/admin/", 
                                    {"username": "hakantrg",
                                     "password": "123456"},
                                    headers={"X-CSRFToken": csrftoken})
        #self.client.get('/polls', cookies=response.cookies)
        #print(response.cookies)
        return response
    @task
    def user_workflow(self):
        self.login()
        self.index()
        self.about()

    def index(self):
        self.client.get("/")
        
    def about(self):
        self.client.get('/polls', cookies=self.locust.client.cookies.get_dict())
    #@task


class WebsiteUser(HttpLocust):
    task_set = WebsiteTasks
    host = "http://localhost:8000"
    min_wait = 5000
    max_wait = 15000
```

### Expected behavior

I try to success request .

### Actual behavior

```
# fails | Method | Name | Type
-- | -- | -- | --
7 | GET | / | HTTPError('404 Client Error: Not Found for url: http://localhost:8000/',)
7 | GET | /polls | HTTPError('404 Client Error: Not Found for url: http://localhost:8000/accounts/login/?next=/polls/',)
```

### Environment settings (for bug reports)

- OS:Wİndows 10
- Python version:3.5
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment] 2019-02-20 15:23
The details will depend on your application under test.

closing.. this is a general question, not a bug/issue.

**Closed by cgoldberg** 2019-02-20 15:23 UTC

**Comment by anm237** [comment] 2020-11-22 10:56
My application accepts only HTTPS traffic. While load testing, I faced this error on the console.

"HTTPError('404 Client Error: Not Found for url: https://[MY_ENDPOINT_URL]/healthcheck')"

Is this because locust tries to send an HTTP request to the application endpoint and it is getting rejected

**Comment by heyman** [comment] 2020-11-23 13:59
@anm237 No, that doesn't sounds like it's related to HTTPS. The `HTTPError` exception does not imply that plain HTTP is used. It sounds like the URL you're requesting returns a 404 Not Found.
