### ISSUE TITLE
RuntimeError: Set changed size during iteration on Python 3.6

### ISSUE THREAD

**Issue by cjw296** [locustio/locust#1174] opened 2019-11-27 18:49 UTC
### Describe the bug

Running a simple locust script on Python 3.6, I occasionally get the following when shutting down locust, either via the red stop button or ctrl-c on the python process:

```
 Traceback (most recent call last):
 File "gevent/pywsgi.py", line 964, in handle_one_response
    self.run_application()
 File "gevent/pywsgi.py", line 911, in run_application
    self.result = self.application(self.environ, self.start_response)
 File "flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
 File "flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
 File "flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
 File "flask/_compat.py", line 39, in reraise
    raise value
 File "flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
 File "flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
 File "flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
 File "flask/_compat.py", line 39, in reraise
    raise value
 File "flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
 File "flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
 File "locust/web.py", line 85, in stop
    runners.locust_runner.stop()
 File "locust/runners.py", line 196, in stop
    for locust_greenlet in self.locusts:
 RuntimeError: Set changed size during iteration
 2019-11-27T18:41:36Z
 {'REMOTE_..., (hidden keys: 26)} failed with RuntimeError
```

### Environment settings

- OS: RHEL 7
- Python version: 3.6.7

- Packages:
```
certifi                 2019.9.11  Python package for providing Mozilla's CA Bundle.
chardet                 3.0.4      Universal encoding detector for Python 2 and 3
click                   7.0        Composable command line interface toolkit
faker                   2.0.4      Faker is a Python package that generates fake data for you.
flask                   1.1.1      A simple framework for building complex web applications.
gevent                  1.5a2      Coroutine-based network library
geventhttpclient-wheels 1.3.1.dev2 Pre-built wheels for geventhttpclient
greenlet                0.4.15     Lightweight in-process concurrent programming
idna                    2.8        Internationalized Domain Names in Applications (IDNA)
itsdangerous            1.1.0      Various helpers to pass data to untrusted environments and back.
jinja2                  2.10.3     A very fast and expressive template engine.
JSON.
locustio                0.13.2     Website load testing framework
markupsafe              1.1.1      Safely add untrusted strings to HTML/XML markup.
msgpack-python          0.5.6      MessagePack (de)serializer.
python-dateutil         2.8.1      Extensions to the standard Python datetime module
pytz                    2019.3     World timezone definitions, modern and historical
pyzmq                   18.1.1     Python bindings for 0MQ
requests                2.22.0     Python HTTP for Humans.
six                     1.13.0     Python 2 and 3 compatibility utilities
text-unidecode          1.3        The most basic Text::Unidecode port
urllib3                 1.25.7     HTTP library with thread-safe connection pooling, file post, and more.
werkzeug                0.16.0     The comprehensive WSGI web application library.
```

**Comment by cyberw** [comment] 2019-11-28 20:20
Hi! Can you share your locust script? How many locusts/clients do you run?

**Comment by cjw296** [comment] 2019-11-28 22:41
I'm afraid not, since it includes credentials and proprietary app stuff.
I get this just running one locust process, no slaves. 
1000 clients, spawn rate of 1000, averaging around 400rps.

**Comment by cyberw** [comment] 2019-11-29 06:21
Thats a super high spawn rate. Have you tried reducing it?

**Comment by cjw296** [comment] 2019-11-29 06:49
These errors occur on shutdown, whether using the stop button or hitting Ctrl-C, I don't think the spawn rate is affecting it. 

Unrelated to this issue, but why is having a high spawn rate bad? you're going to end up with whatever number of clients in the end anyway, right?

**Comment by cyberw** [comment] 2019-11-29 07:59
Spawning lots of clients in a short time may overload your load generator CPU or cause os/network level issues/bottlenecks because of all the new sockets being opened in such short interval (client and/or server side). 

Lots of people have reported issues with high rampup, maybe we should add a warning output for it in locust.. What do you think @heyman ? Maybe warn if ramp up is >100 per locust process?

**Comment by cjw296** [comment] 2019-12-01 22:15
Or just put a limit on it?
That said, why would high ramp up have an effect that occurs only during shutdown?

**Comment by cyberw** [comment] 2019-12-01 22:32
Not sure, but it appears a lot of things can break. Can you reproduce your error with a slow (lets say 25/s) rampup?

**Comment by cjw296** [comment] 2019-12-01 22:34
I've already dropped to 100, will let you know what I see.

**Comment by cjw296** [comment] 2019-12-03 20:57
Hmm, not seen this since dropping the pawn rate, but surprised that has an impact on shutdown. 
Should we re-purpose this bug to be to add a warning, or better, a hard limit on the number of clients that can be spawned at once?

**Comment by cyberw** [comment] 2020-01-16 15:13
Closing this (because there is a workaround) 

My proposed PR doesnt actually fix the issue (just adds a warning), so it is more fair that I close it here instead of having the merge of the PR fix it :)

**Closed by cyberw** 2020-01-16 15:13 UTC
Labels: bug, invalid
