### ISSUE TITLE
Strange behavior of "Total Requests per Second" chart

### ISSUE THREAD

**Issue by hoangphucITJP** [locustio/locust#889] opened 2018-09-19 01:40 UTC
### Description of issue

Total Requests per Second's RPS drop to below 1 after the test start a while despite the RPS number on top keep rising

### Expected behavior

The RPS of Total Requests per Second chart  should keep updating according to the RPS number on top

### Actual behavior

The RPS of Total Requests per Second chart value does not match the RPS number on top after the test start a while

### Environment settings (for bug reports)

- OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-78-generic x86_64)
- Python version: 2.7.12
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

I don't know what to put here but feel free to ask for any extra information. I can't provide the code though

### Screenshot

![imgpsh_fullsize](https://user-images.githubusercontent.com/14938527/45725860-f873a200-bbe6-11e8-8fcf-3487d0afe8cc.png)

P/s: Sorry for ignored the template.

**Comment by klloveall** [comment] 2019-02-07 06:06
I have also encountered this issue. I dug into the responses and it's happening because the `/stats/request` endpoint stops returning the `"Total"` stat block at the end of the `stats` list. This then causes the graph to show a RPS from a random path instead of from the total like it should. Interestingly, as is shown in the screenshot from @hoangphucITJP, the RPS in the header is still correct.

I tried to dig into the Python code and figure out what's causing it there, but haven't had much success there yet (mostly b/c I'm only running this in AWS, not locally so my debugging options are somewhat limited).

Please let me know if there's any suggestions as to how to solve this or any other debugging information I can provide.

**Comment by supermasita** [comment] 2019-03-09 00:08
@cgoldberg I think my simple change should work as a fix (it has solved the issue for me). Thanks.

**Comment by supermasita** [comment] 2019-03-11 23:30
@hoangphucITJP @klloveall - let me know if manually applying my change fixes your issue. I think my PR is correct, but it is not building for unrelated reasons. Thanks.

**Comment by sweetib** [comment] 2019-06-24 08:59
we are also facing this issue, when is the PR supposed to be merged?

**Comment by victor61zhong** [comment] 2019-09-12 05:33
any update for this issue ?

**Comment by canstudios-simonm** [comment] 2019-10-01 08:29
I also see the RPS drop off as shown in the graph every time we run Locust. It makes tracking the average RPS value over a run very hard without it working.

**Comment by cyberw** [comment] 2019-10-20 08:24
I cant reproduce this (on MacOS, using locust 0.12.1). Is this only an issue on Linux? Or is it something related to the test plan?

![image](https://user-images.githubusercontent.com/1134328/67156827-c1108100-f323-11e9-9126-e64be14ecc1c.png)

**Comment by heyman** [comment] 2019-10-20 08:33
I believe this could have the same cause to #1060 which has now been fixed.

**Closed by heyman** 2019-10-20 08:33 UTC
Labels: Hacktoberfest, bug

**Comment by subbro** [comment] 2021-03-08 05:17
Hi, I am unable to understand how this total request per second is calculated? Can someone please explain this? I am new to locust
