### ISSUE TITLE
Stderr connection error ( python3.6), but no failures on UI

### ISSUE THREAD

**Issue by neelay** [locustio/locust#625] opened 2017-07-21 10:58 UTC
I start with 5000 users to simulate at a hatch rate of 500, but the test only goes to 4200.
Result in UI shows no failures, but stderr shows the following failures.
Can any help on how to fix the failures.

`locustio==0.8a1`
<img width="1191" alt="screen shot 2017-07-21 at 4 17 16 pm" src="https://user-images.githubusercontent.com/1371841/28460821-707a389a-6e31-11e7-8b2b-6dff52814782.png">
`requests==2.12.4`

```shell
[2017-07-21 16:17:47,559] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,559] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/locust/runners.py", line 115, in start_locust
    locust().run()
[2017-07-21 16:17:47,559] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,559] myMachine/ERROR/stderr: File "/ENV3/lib/python3.6/site-packages/locust/core.py", line 104, in run
    self.task_set(self).run()
[2017-07-21 16:17:47,559] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/locust/core.py", line 252, in run
    self.on_start()
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ locustTest.py", line 56, in on_start
    self.token = loginUser()
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ helper.py", line 18, in loginUser
    'Accept':'application/json'
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: File "/ ENV3/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: 
[2017-07-21 16:17:47,560] myMachine/ERROR/stderr: <Greenlet at 0x1208a9800: start_locust(<class 'locustTest.WebsiteUser'>)> failed with ConnectionError```

**Comment by aldenpeterson-wf** [comment] 2017-07-21 15:02
You probably are hitting an exception, rather than a failure. Check that tab.

**Comment by neelay** [comment] 2017-07-25 07:19
exceptions tab is empty. these errors were only seen on terminal.

**Comment by aldenpeterson-wf** [comment] 2017-09-08 16:13
Is there a way to consistently reproduce this?

**Comment by mbeacom** [comment] 2017-11-15 04:07
@neelay Any update on this? Can you outline methods to reproduce this error?

**Comment by cgoldberg** [comment] 2017-12-18 14:48
closing since there are no updates on this issue

**Closed by cgoldberg** 2017-12-18 14:48 UTC
Labels: needs reproducing, waiting on contributor
