### ISSUE TITLE
Official docker image does not actually exist

### ISSUE THREAD

**Issue by coderanger** [locustio/locust#1092] opened 2019-09-26 17:59 UTC
The image mentioned in the docs (https://docs.locust.io/en/stable/running-locust-docker.html#add-your-tests) does not actually exist. Or rather, it exists but has no versions: https://hub.docker.com/r/locustio/locust

**Comment by max-rocket-internet** [comment] 2019-09-27 08:15
Duplicate of https://github.com/locustio/locust/issues/849

**Closed** 2019-09-29 20:13 UTC
