### ISSUE TITLE
(libev) select: Invalid argument when trying to go past 1k users

### ISSUE THREAD

**Issue by TTimo** [locustio/locust#121] opened 2013-12-27 16:37 UTC
MacOS X 10.9, python 2.7 (macports)
Latest locust (github), latest pip packages

Testing a local setup, trying to break past 1000 users. I'm able to load up to 1000 users just fine (after bumping my ulimit), but locust crashes out past that point:

https://gist.github.com/TTimo/8149351

**Comment by justiniso** [comment] 2017-02-13 21:44
Can anyone confirm if this is still an issue? I'm not able to reproduce with my MBP: libev 4.22 (installed with brew, not macports though)

**Comment by xbonio** [comment] 2017-12-02 11:22
I confirm this on macOS High Sierra with libev 4.24 (bottled).
Everything seems to work fine with 1000 users, however changing it to 1025 users results in:

```
[2017-12-02 12:19:09,562] iMac.local/ERROR/stderr: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/locust/core.py", line 271, in run
    self.execute_next_task()
  File "/Library/Python/2.7/site-packages/locust/core.py", line 297, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Library/Python/2.7/site-packages/locust/core.py", line 309, in execute_task
    task(self, *args, **kwargs)
  File "/Users/mikolaj/Desktop/hello/locust/locustfile.py", line 7, in index
    self.client.get("/")
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/locust/clients.py", line 114, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/locust/clients.py", line 158, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 248, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/util/connection.py", line 34, in is_connection_dropped
    return select([sock], [], [], 0.0)[0]
  File "/Library/Python/2.7/site-packages/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
```

**Comment by cgoldberg** [comment] 2017-12-03 15:26
> I confirm this on macOS High Sierra with libev 4.24 (bottled).

this is actually different than the original issue described.  You are receiving a totally different stacktrace.

> ValueError: filedescriptor out of range in select()

Have you increased file descriptors in your OS?  If not, you need to.

This may be considered a bug in gevent, requests, or urllib3 for not handling the situation gracefully when you run out of file descriptors...  but I don't see an actual Locust issue we can take action on besides aborting a test once you exhaust file descriptors.

I am closing this issue for now since there is nothing actionable to fix for Locust.

**Closed by cgoldberg** 2017-12-03 15:26 UTC
Labels: needs reproducing
