### ISSUE TITLE
Add tag in web ui

### ISSUE THREAD

**Issue by liorazroel** [locustio/locust#1722] opened 2021-03-03 18:05 UTC
Hey, 
I had idea to new feature: to add tags option under the input of host in web ui. 

Its's possible? 

I think its will be very useful.

**Comment by aek** [comment] 2021-03-03 18:40
I like the idea, but I think that it will need some locust redesign(commented in another issue) to be able to introduce this kind of changes

**Comment by aek** [comment] 2021-03-03 18:42
Duplicate of #1695

**Closed** 2021-03-03 19:29 UTC
Labels: duplicate, feature request
