### ISSUE TITLE
How to fix Coordinated Omission Problem in Locust

### ISSUE THREAD

**Issue by sukhbir-singh** [locustio/locust#2347] opened 2023-05-17 21:19 UTC
### Describe the bug

I am running locust in distributed mode for testing my backend service. I have observed one pattern that after every fix interval, I can see some dip in number of requests made to backend service. As far as I know, this is known as coordinated omission problem. Because of this I am getting incorrect rps value at the end of test run.

### Expected behavior

Test run should keep on working as expected. There should not be regular dips in locust requests to backend service. 

### Actual behavior

See the graph I am attaching with his issue. You will see the frequent dips in requests.

### Steps to reproduce
 

I think this is happening when 100 percent requests are failing. I have also seen this when all requests were not failing as well. But it's more common when all requests were failing.

![image](https://github.com/locustio/locust/assets/13816752/08330598-6940-490d-aa8f-4c0f19fcc581)

### Environment

- OS: Windows 11
- Python version: 3.12
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds): Latest
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment] 2023-05-17 22:16
What are your response times? If response times are increasing around the times you also see decreased rps, then this is normal and caused by your system being slow.

see https://github.com/locustio/locust/wiki/FAQ#increase-my-request-raterps
and/or maybe switch to a rps limited (constant_throughput/ips wait time)

**Comment by cyberw** [comment] 2023-05-17 22:16
Closing as this is most likely not a bug. Questions go to stackoverflow or slack

**Comment by emanuelef** [comment] 2023-05-22 15:08
Hi, related to the Slack channel, I was trying to sign up to the Slack channel here: https://slack.locust.io. But I get Error:Error: certificate has expired.
Is there a new signup link ?

**Closed** 2023-06-04 17:28 UTC
Labels: bug, invalid
