### ISSUE TITLE
UI shows STOPPED when it is running

### ISSUE THREAD

**Issue by rvernica** [locustio/locust#1153] opened 2019-11-15 22:43 UTC
## Describe the bug

After starting a _New test_ the UI still shows that Locust is STOPPED, but Locust is running fine. See screenshot:
![Locust-stopped](https://user-images.githubusercontent.com/241185/68980583-b5469c00-07b5-11ea-9640-ff4fac805294.png)

### Steps to reproduce

I've run into this bug a couple of times already but I am not able to construct a sequence of steps to reproduce it every time. It seem to be related to the fact that I stop a test and then I start a new one.

### Environment settings

- OS: CentOS Atomic 8 1905
- Python version: python:3.7.5-slim-buster (Docker image)
- Locust version: 0.12.2
- UI OS: Fedora 30
- UI Browser: Firefox 70.0

**Comment by heyman** [comment] 2019-11-15 23:51
Do you see any exceptions (not originating from your test code) in any of the slave processes or the master process?

**Comment by heyman** [comment] 2019-11-15 23:54
Also, do you see any JavaScript errors in the browser? What happens if you reload the page, does it still say STOPPED?

**Comment by max-rocket-internet** [comment] 2019-11-18 16:15
I also see this.

> do you see any JavaScript errors in the browser?

Nope.


> What happens if you reload the page, does it still say STOPPED?

Yes. It's still ramping up.

![Screen Shot 2019-11-18 at 17 10 38](https://user-images.githubusercontent.com/8859277/69069362-a0247400-0a26-11ea-985d-3c9227095de8.png)

I clicked STOP and see this in slave logs:

```
 [2019-11-18 16:08:16,489] locust-opa-slave-86cf6df9fb-tlmn4/INFO/locust.runners: Killing 50 locusts                                                                                                                       │
│ [2019-11-18 16:08:16,785] locust-opa-slave-86cf6df9fb-tlmn4/INFO/locust.runners: Killing 33 locusts
```

I have to delete all pods to stop them. No errors or exceptions from master or slaves.

**Comment by max-rocket-internet** [comment] 2019-11-18 16:16
I'm using `0.13.1`

**Comment by ernestom** [comment] 2019-11-22 22:23
I've also seen this behavior in distributed mode in 0.12.2.

**Comment by cyberw** [comment] 2019-12-30 20:39
Hi! We need to narrow this down before we can really identify this issue. Is it somehow related to the number of locusts? Or is it happening every time for you? Can you reproduce it with the latest version?

**Comment by cyberw** [comment] 2020-01-19 20:37
Nobody has provided any further details, so I'm closing this. The only common denominator for when this error happens seems to be docker?

**Closed by cyberw** 2020-01-19 20:37 UTC
Labels: bug, invalid, waiting on contributor
