### ISSUE TITLE
Unable to run the locustfile example 

### ISSUE THREAD

**Issue by RanPollak** [locustio/locust#607] opened 2017-06-20 10:47 UTC
Hi, 
After install locust on Centos 7 i've configured the  locustfile and try to run it from the CLI, PSB.

[root@qa-machine locust]# locust --host=http://example.com
[2017-06-20 13:38:34,083] qa-machine/INFO/locust.main: Starting web monitor at *:8089
[2017-06-20 13:38:34,222] qa-machine/ERROR/stderr: Traceback (most recent call last):
[2017-06-20 13:38:34,222] qa-machine/ERROR/stderr: File "/bin/locust", line 9, in <module>
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: 
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: load_entry_point('locustio==0.7.5', 'console_scripts', 'locust')()
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: File "/usr/lib/python2.7/site-packages/locust/main.py", line 437, in main
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: 
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: gevent.signal(signal.SIGTERM, sig_term_handler)
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: File "/usr/lib64/python2.7/site-packages/gevent/__init__.py", line 101, in __new__
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: 
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: return _signal_class(*args, **kwargs)
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 265, in __init__
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: 
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: self.watcher = self.hub.loop.signal(signalnum, ref=False)
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: File "core.pyx", line 472, in gevent.core.loop.signal (gevent/gevent.core.c:8594)
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: File "core.pyx", line 1127, in gevent.core.signal.__init__ (gevent/gevent.core.c:19277)
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: AttributeError
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: :
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr: 'module' object has no attribute 'NSIG'
[2017-06-20 13:38:34,223] qa-machine/ERROR/stderr:

**Comment by aldenpeterson-wf** [comment] 2017-08-18 16:05
Duplicate of https://github.com/locustio/locust/issues/518

closing

**Closed by aldenpeterson-wf** 2017-08-18 16:05 UTC
