### ISSUE TITLE
Put a big sign "you must reload this page before any stats are displayed" somewhere on the web interface

### ISSUE THREAD

**Issue by davidavdav** [locustio/locust#893] opened 2018-09-27 10:04 UTC
### Description of issue / feature request

On [http://localhost:8089](http://localhost:8089) I see start / stop buttons, and they work.  But apart from that, nothing happens.  RPS stays 0.  The cmdline says number of locusts hatched.  But that is is.  I can click around on the tabs.  They all show blank graphs / stats.  I am getting confused.  I try different locustfiles.  Same behaviour. I try literal examples from the docs.  Same stuff.  Nothing happens on the web interface.  I seriously start to doubt myself.  I spend an hour of two getting more frustrated.  How is it possible that _no one else_ seems to have similar issues?

Then I see the remark somewhere "Note: There is no persistence of these charts, if you refresh this page, new charts will be created".  Maybe I should reload the page.  I do so.  And wonder of all wonders: stats start appearing and graphs starts to be plotted. 

### Expected behavior

After pressing start, graphs and stats start being updated.  Or there is a big sign saying: "you need to press reload if you want to see something happen".  

### Actual behavior

nothing happens in the web interface.  everything stays at 0 / blank. 

### Environment settings (for bug reports)

- OS: macos / chrome browser
- Python version: 2.7
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

start from scratch with a new--possibly somewhat broken---locustfile, that you then try to fix.

**Comment by cgoldberg** [comment] 2018-09-29 01:08
> start from scratch with a new--possibly somewhat broken---locustfile, that you then try to fix.

since the steps to reproduce don't make sense, I am closing this.

contributions for improvement are welcome
(please keep issue reports concise with clear reproducible steps).

**Closed by cgoldberg** 2018-09-29 01:08 UTC
