### ISSUE TITLE
This is a suggestion. In order to better use the custom client system stress test, we may need more examples

### ISSUE THREAD

**Issue by chineseluo** [locustio/locust#1515] opened 2020-08-13 08:37 UTC
Can you give me some examples of using other client systems? We analyze the official cases in use, but we don't understand it very well. Maybe there is too little information on the Internet. Thank you！

**Comment by cyberw** [comment] 2020-08-14 07:39
Hi! I think this is a duplicate of #1423. I've linked some examples from locust-plugins there though.

**Comment by chineseluo** [comment] 2020-08-14 07:49
Thank you. I will recommend your framework around

**Closed** 2020-08-14 07:55 UTC
Labels: duplicate, feature request
