### ISSUE TITLE
ConnectionError(ProtocolError('Connection aborted.', BadStatusLine("''",)),)

### ISSUE THREAD

**Issue by vinayrajalur** [locustio/locust#308] opened 2015-07-23 06:20 UTC
Hi Team,

I  am are trying load test SSO(Single sign-on) flow with our server. For some of the requests i am getting "ConnectionError(ProtocolError('Connection aborted.', BadStatusLine("''",)),)". When i try to read the response it as Status Code 0 and no header fields. As the error says its due the connection aborted. can you please help me what is causing this issue?. 
i have seen issue happens for response time of within 1 sec.

**Comment by heyman** [comment] 2015-07-26 09:41
Hi!

Does it work if you just use plain Python and Requests (http://docs.python-requests.org/en/latest/)?

**Comment by vinayrajalur** [comment] 2015-07-29 05:35
Hi Heyman,

i tried to using only Requests and issue happens after 2050 requests , i am using gevent to send 10 concurrent requests at a time. following is the traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "test_BadStatusLine.py", line 16, in get_resp
    resp = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
<Greenlet at 0x239ab90: get_resp('<url>)> failed with ConnectionError

Traceback (most recent call last):
  File "test_BadStatusLine.py", line 27, in <module>
    pool.map(get_resp,urls)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/pool.py", line 169, in map
    return list(self.imap(func, iterable))
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/pool.py", line 293, in next
    raise value.exc
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))

i run locust in parallel with the above script , here issue is happening for every 10 - 20 requests.

**Comment by vinayrajalur** [comment] 2015-08-11 13:36
Any update on this issue?

**Comment by vividhsv** [comment] 2015-08-11 22:30
Looks like this an error from httplib.
Looks like the issue is fixed on python 3.5. However, it is still an issue on python 2.7

Get more info on the following links
https://github.com/kennethreitz/requests/issues/2364
https://bugs.python.org/issue23054

**Comment by kevbo** [comment] 2016-01-25 17:07
FWIW, I was able to prevent this error by reducing the max_wait time so that the worker wouldn't exceed the timeout on the keep-alive connection (see https://bugs.python.org/msg103545)

**Closed** 2016-04-02 02:15 UTC

**Comment by vadi2** [comment] 2018-07-18 07:40
What did you reduce max_wait to?

**Comment by meldehi** [comment] 2018-08-09 23:53
I am hitting the same issue. I am using python 3.7. It starts happening once I hit the max number of clients. I tried putting down the max_wait and min_wait time to 50 but that does not help as well.

**Comment by samuelralak** [comment] 2019-06-06 07:51
any update on this issue? am in the same predicament as @meldehi, using Python 3.7

**Comment by ddorian** [comment] 2019-06-06 08:36
Create a global Connection Pooler for requests and attach it to `self.locust.client` whenever the LocustUser is started (by overriding __init__). That fixed it in my case

**Comment by ddorian** [comment] 2019-06-06 09:43
Also, add timeouts to calls from requests `self.client` to see if the host isn't responding so they don't hang forever.
