### ISSUE TITLE
Only the first user class is being spawned when running locust as library

### ISSUE THREAD

**Issue by rkhir** [locustio/locust#1635] opened 2020-11-20 20:26 UTC
### Describe the bug
I'm running Locust as a library, when instantiating the environment, only the first user class gets spawn up 

### Expected behavior
All user classes should be span up with the right amount of stimulated users
### Actual behavior

only the first specified used class in the environment is being spawned
### Steps to reproduce

please see the code snippet

### Environment

- OS: MacOS
- Python version: 3.7
- Locust version:  image "1.2.3"
- Locust command line that you ran: running locust as a library in a main method
- Locust file contents (anonymized if necessary):

user class A
```
class AUsers(HttpUser):
    host = os.environ.get("A_HOST")
    wait_time = constant_pacing(1)
    tasks = [ATask]

```
User class B 
```
class BUser(HttpUser):
    host = os.environ.get("B_HOST")
    wait_time = constant_pacing(1)
    tasks = [Btasks]

```

Master main module : 
```
    env = Environment(user_classes=[BUser,AUser])

    def run_manager(self):
        logging.info('*******************')
        logging.info('{}'.format("Starting Manager"))
        logging.info('*******************')
        self.env.step_load = True
        self.env.create_master_runner()
        self.env.create_web_ui("0.0.0.0", 8089)
        gevent.spawn(stats.stats_history, self.env.runner)
        self.env.runner.greenlet.join()

if __name__ == "__main__":
    manager = ManagerEnv()
    manager.run_manager()
```

Worker main module
```
    env = Environment(user_classes=[BUser,AUser])

    def run_worker(self):
        logging.info('*******************')
        logging.info('{}'.format("Starting Worker"))
        logging.info('*******************')
        self.env.create_worker_runner(os.environ.get('MANAGER_HOST'), 5557)
        gevent.spawn(stats_printer(self.env.stats))
        self.env.runner.greenlet.join()


if __name__ == "__main__":
    worker = Worker()
    worker.run_worker()

```

**logs : 
/INFO/locust.runners: All users spawned: BUser: 1, AUser: 0 (4 already running)**

**Comment by mboutet** [comment] 2020-11-20 21:48
Are you stepping 1 user at a time until you reach 5? If so, then it's a known problem. It is actually related to https://github.com/locustio/locust/issues/1618 and I've created a PR https://github.com/locustio/locust/pull/1621 that should solve this issue. As a temporary workaround, you could ensure to increase the users by at least 2 at each step. You will then have 50% of `AUser` and 50% of `BUser`.

**Comment by cyberw** [comment] 2020-11-26 18:38
@rkhir We need more details. I'm closing this for now, as you have not replied to @mboutet :s comment, but feel free to reopen.

**Closed by cyberw** 2020-11-26 18:38 UTC
Labels: bug

**Comment by rkhir** [comment] 2020-12-01 16:29
@cyberw @mboutet apologies for the late response.
@mboutet thank you for the workaround that worked; I've noticed that the number of spawned users in the initial **Spawn rate** and **Number of users to increase by step** has to be equal to the number of user classes; otherwise, only the first user class will be spawned, and the other user classes will be ignored. Unfortunately, I'm using the official docker image. Therefore, I cant pip install your branch.

**Comment by mboutet** [comment] 2020-12-01 17:00
@rkhir, you can build the image for my branch using this command:
```shell
pushd "$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')" && \ 
  git clone https://github.com/mboutet/locust.git && pushd locust && git checkout -b users-distribution && \
  docker build . --tag locust:pr-1621 && \
  popd && popd
```
This will clone into a temp directory and build the image. You can then use `locust:pr-1621`.

**Comment by rkhir** [comment] 2020-12-02 19:28
Thank you, @mboutet. Unfortunately, I'm using Bazel to build my images. 
I will look for a workaround to check out your branch, build the image, and test the changes.

**Comment by rkhir** [comment] 2020-12-11 19:58
@mboutet, I was able to run your image. for some reason I couldn't run locust in step mode any more.
 and the issue wasn't resolved, when providing number of users to spawn = (number of users classes +1)
example: 

total number of userClasses = 2 
total number of users to spawn = 3
spawn rate = 3
[locust-worker-6dbb866d68-psb55 locust-worker]  locust-worker-6dbb866d68-psb55/INFO/locust.runners: All users spawned: AUser: 1, BUser: 2 (3 total running)

**Comment by mboutet** [comment] 2020-12-11 20:36
@rkhir, the step mode no longer exists since https://github.com/locustio/locust/releases/tag/1.3.0 (i.e. before I even implemented my changes).

What do you mean the issue is not resolved? You have 1 `AUser` and 2 `BUser` running for a total of 3 users which is the expected behaviour of my changes.

**Comment by rkhir** [comment] 2020-12-11 20:44
@mboutet Thank you for the update, I wasn't aware that step mode was deprecated since I'm still using `1.2.3`
yes, the total number of users is correct but, shouldn't be the number of users per userClass?

**Comment by mboutet** [comment] 2020-12-11 21:45
You mean 3 of `AUser` and 3 of `BUser`? If so, then it's not (and never have been as far as I know) how locust compute the number of users to spawn. The total number of users is shared between the different user classes. So if you have 4 total users and 2 user classes with equal weights, you should get 2 users of each class. You can look at the documentation here https://docs.locust.io/en/stable/writing-a-locustfile.html#user-class.

Thus, if you wish to have 3 users of each class in your case, you should set the total number of users to 6.

**Comment by rkhir** [comment] 2020-12-14 20:31
Thank you @mboutet, for elaborating. in that case the I can say my original issue is resolved and I can't wait for it to be merged. nicely done!

**Comment by anthammas** [comment] 2021-07-25 09:44
@rkhir Just a trivial question. How do you set the MANAGER_HOST? Any fixed value?

**Comment by rkhir** [comment] 2021-08-09 13:39
> @rkhir Just a trivial question. How do you set the MANAGER_HOST? Any fixed value?

@naveen-kinnal, it's an environment variable for the Manager's URL.
